# Generated by Django 5.1.7 on 2025-03-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_normalwallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='balance_kz',
            new_name='balance',
        ),
        migrations.DeleteModel(
            name='NormalWallet',
        ),
    ]
