# Generated by Django 5.1.7 on 2025-03-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_rename_balance_kz_wallet_balance_delete_normalwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
