"""
Django settings for Wallet project.

Generated by 'django-admin startproject' using Django 4.2.17.
For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Carrega variáveis do .env
load_dotenv()

# BASE_DIR: diretório raiz do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# Configuração do ambiente
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Wallet.settings')

# 🔐 Chave secreta (mantenha em segredo em produção!)
SECRET_KEY = os.getenv('SECRET_KEY')

# 🔥 Debug: deve ser False em produção!
DEBUG = os.getenv("DEBUG") == "True"

# 🌐 Hosts Permitidos: utilize variáveis de ambiente para maior flexibilidade
ALLOWED_HOSTS = ["*"]

# Aplicações Instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'contas.apps.ContasConfig',
    'investimento',
    'channels',
    'corsheaders',
    'whitenoise.runserver_nostatic',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

# Configuração de URL
ROOT_URLCONF = 'Wallet.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Certifique-se de que está apontando para a pasta correta
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Aplicação WSGI (para deploy tradicional) e ASGI (para Channels)
WSGI_APPLICATION = 'Wallet.wsgi.application'
ASGI_APPLICATION = 'Wallet.asgi.application'

# Database: utilizando dj_database_url para facilitar configurações via variável de ambiente
DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
}

# Validação de Senhas
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internacionalização
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Arquivos Estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Configuração do usuário personalizado
AUTH_USER_MODEL = 'contas.CustomUser'

# Chave de Criptografia (se necessário)
ENCRYPTION_KEY = os.environ.get("ENCRYPTION_KEY")

# Configuração do CORS
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "https://skillwallet.netlify.app").split(",")

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOW_HEADERS = ["content-type", "authorization", "X-CSRFToken"]

# Configuração do Django REST Framework e SimpleJWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Configuração do Channels (ex: usando Redis)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL", "redis://127.0.0.1:6379")],
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Se desejar, pode expor a aplicação ASGI para uso com servidores ASGI:
# (Esse comando é opcional se o seu arquivo asgi.py já define a variável 'application')
# application = get_asgi_application()
